name: banter
services:
  web:
    build: .
    ports:
      - 5050:5000
  db:
    image: mariadb:10.9.2
    restart: always
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    volumes:
      - banter-db-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
volumes:
  banter-db-data:
    driver: local