---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: banter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banter
  template:
    metadata:
      labels:
        app: banter
    spec:
      containers:
        - name: banter
          image: docker.io/library/banter-web
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_PATH
              value: "mysql+pymysql://root:admin@banter-db-svc/banter"
            - name: SECRET_KEY
              value: "secret"
---
apiVersion: v1
kind: Service
metadata:
  name: banter-app-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: banter
  type: LoadBalancer