# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mariadb-pv
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 2Gi
#     storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /var/lib/mysql
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mariadb-pvc
# spec:
#   storageClassName: standard
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#       volumeName: mariadb-pv
#       storageClassName: standard